version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    volumes:
      - zookeeper_data:/opt/zookeeper-3.4.13/data
      - zookeeper_log:/opt/zookeeper-3.4.13/conf
  kafka:
    image: wurstmeister/kafka
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
#      KAFKA_LOG_DIRS: /kafka/logs-1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "input:6:1,values:6:1,state:6:1"
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/kafka/logs-1
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
#      - ./sql/:/docker-entrypoint-initdb.d/
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  connect:
    image: strangesast/fanuc_driver-connect
    network_mode: host
    build:
      context: .
      dockerfile: docker/connect/Dockerfile
    environment:
      - KAFKA_HOSTS=kafka:29092
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - DATABASE_URL=postgresql://postgres:5432/testing
      - FLUSH_INTERVAL=1000
  schema-registry:
    image: confluentinc/cp-schema-registry:6.0.0
    network_mode: host
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
  driver0:
    image: strangesast/fanuc_driver
    restart: unless-stopped
    environment:
      - KAFKA_BROKERS=kafka:29092
      - DEVICE_IP=10.0.0.200
    build:
      context: .
      dockerfile: Dockerfile
  driver1:
    image: strangesast/fanuc_driver
    restart: unless-stopped
    environment:
      - KAFKA_BROKERS=kafka:29092
      - DEVICE_IP=10.0.0.207
    build:
      context: .
      dockerfile: Dockerfile
  driver2:
    image: strangesast/fanuc_driver
    restart: unless-stopped
    environment:
      - KAFKA_BROKERS=kafka:29092
      - DEVICE_IP=10.0.0.208
    build:
      context: .
      dockerfile: Dockerfile
  driver3:
    image: strangesast/fanuc_driver
    restart: unless-stopped
    environment:
      - KAFKA_BROKERS=kafka:29092
      - DEVICE_IP=10.0.0.209
    build:
      context: .
      dockerfile: Dockerfile
  driver4:
    image: strangesast/fanuc_driver
    restart: unless-stopped
    environment:
      - KAFKA_BROKERS=kafka:29092
      - DEVICE_IP=10.0.0.206
    build:
      context: .
      dockerfile: Dockerfile
  driver5:
    image: strangesast/fanuc_driver
    restart: unless-stopped
    environment:
      - KAFKA_BROKERS=kafka:29092
      - DEVICE_IP=10.0.0.112
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  db_data:
    external: true
  kafka_data:
    external: true
  zookeeper_log:
    external: true
  zookeeper_data:
    external: true
