FROM bitnami/spark:3.0.1

RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.0.1/spark-sql-kafka-0-10_2.12-3.0.1.jar \
  --output /opt/bitnami/spark/jars/spark-sql-kafka-0-10_2.12-3.0.1.jar
